config/routes.rb
Rails.application.routes.draw do
  post '/subscribe', to: 'subscribe#create', as: 'subscribe'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController
  def create
    email = params[:email]

    if EmailValidator.valid? email
      mailchimp = Mailchimp::API.new ENV['mailchimp_api_key']
      mailchimp.lists.subscribe ENV['mailchimp_list_id'], 'email' => email

      render json: { message: 'success' }.to_json, status: :ok
    else
      render json: { message: 'invalid email' }.to_json, status: :bad_request
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_favicons.html.erb
<% %w(57 72 114 120 152).each do |size| %>
  <%= favicon_link_tag "favicons/apple-touch-icon-#{size}x#{size}.png",
    rel: 'apple-touch-icon-precomposed',
    type: 'image/png'
  %>
<% end %>

<% %w(16 32).each do |size| %>
  <%= favicon_link_tag "favicons/favicon-#{size}x#{size}.png", rel: 'icon' %>
<% end %>

app/views/layouts/_meta.html.erb
<%# Templates %>
<%# https://scotch.io/quick-tips/all-search-and-social-media-meta-tags-starter-template%>

<%# TODO: Move this to i18n %>

<% title = "Billion - Changing the way the world crowdfunds. For good." %>
<% description = "Billion is a competitive crowdfunding platform for social good." %>
<% image = image_url('share-image.png') %>


<title><%= title %></title>
<meta name="description" content="<%= description %>">
<link rel="canonical" href="<%= root_url %>">

<!-- Social: Twitter -->
<meta name="twitter:card" content="Billion Effect">
<meta name="twitter:site" content="@BillionEffect">
<meta name="twitter:description" content="<%= description %>">
<meta name="twitter:image:src" content="<%= image %>">

<!-- Social: Facebook / Open Graph -->
<meta property="og:url" content="<%= root_url %>">
<meta property="og:type" content="website">
<meta property="og:title" content="<%= title %>">
<meta property="og:image" content="<%= image %>"/>
<meta property="og:description" content="<%= description %>">
<meta property="og:site_name" content="BillionEffect">

<!-- Social: Google+ / Schema.org  -->
<meta itemprop="name" content="<%= title %>">
<meta itemprop="description" content="<%= description %>">
<meta itemprop="image" content="<%= image %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <%= render 'layouts/meta' %>

  <link href='http://fonts.googleapis.com/css?family=Righteous|Muli:300,400' rel='stylesheet' type='text/css'>

  <%= render 'layouts/favicons' %>

  <%= stylesheet_link_tag 'application', media: 'all',
    'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <% if Rails.env.development? %>
    <% ga_version = 'analytics_debug.js' %>
  <% else %>
    <% ga_version = 'analytics.js' %>
  <% end %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/<%= ga_version %>','ga');

    ga('create', 'UA-63353165-1', 'auto');
    ga('send', 'pageview');
  </script>
</head>
<body>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/landing.html.erb
<script>
  window.config = window.config || {};
  window.config.subscribePath = '<%= subscribe_path %>';
  window.config.authenticityToken = '<%= form_authenticity_token %>';
</script>
<div class='masthead-container'>

  <nav class="navbar navbar-default navbar-landing navbar-non-sticky hidden-xs">
    <div class="container">
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#landing-about">About</a></li>
          <li><a href="#landing-columbus">Where</a></li>
          <li><a href="#landing-team">Team</a></li>
          <li><a href="#landing-join" class='navbar-cta'><span>Join The Movement</span></a></li>
        </ul>
      </div>
    </div>
  </nav>

  <nav class="navbar navbar-default navbar-landing navbar-fixed-top navbar-sticky visible-xs">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <span class='navbar-left-container' style='opacity: 0'>
          <%= link_to '#landing-jumbotron', class: 'navbar-brand' do %>
            <%= image_tag 'billion_logo_small.png', class: 'logo-small' %>
          <% end %>
          <button type='button' class='btn play-btn navbar-btn'
            data-toggle="modal" data-target="#modalVideo" >
            <%= icon('play-circle') %>
            <span class="play-text">Watch our Video</span>
          </button>
        </span>
      </div>

      <div class="collapse navbar-collapse" id="nav-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#landing-about">About</a></li>
          <li><a href="#landing-columbus">Where</a></li>
          <li><a href="#landing-team">Team</a></li>
          <li><a href="#landing-join" class='navbar-cta'><span>Join The Movement</span></a></li>
        </ul>
      </div>
    </div>
  </nav>

  <section id="landing-jumbotron" class="jumbotron jumbotron-landing">
    <div class="container">
      <div>
        <%= image_tag 'billion_logo_large.png', class: 'logo-large' %>
      </div>

      <p class="tag-line">Changing the way the world crowdfunds. For&nbsp;good.</p>

      <div>
        <button class='play-btn btn' data-toggle="modal"
        data-target="#modalVideo"><%= icon('play', 'Watch the video') %></button>
      </div>

    </div>
  </section>

  <div class='landing-image-credit'>
    <a href='https://www.flickr.com/photos/neallindsay/491850284/in/photolist-5Jdbg7-5J8YZZ-ameWA1-9oA7wy-9owMoT-9ox1PH-n1TmTX-n1V3aG-nzsyEG-7SuicL-gE4nEV-a5cnhp-paYPkv-bxoLm7-psumeM-7fDGiQ-8uxL6h-KsRXj-5NCLro-jXQiX-7fDGuW-7fzPd8-7fDGrJ-7fDGcu-7fDGAu-7fDGDU-7fDG9u-7fzP14-7fDH2j-7fzNPg-7fzP3p-7fzPaP-7fzP5a-7fDGfo-7fDGSj-7fzNEp-2VCALZ-pnQii-5xM6zR-r4iK5h-7Kmz7w-4aUst2-iYghH-2iSF9T-g7NK5L-o443QM-8hv6hq-fP5rqW-9QfzPm-9oAakJ'>Image by Neal Lindsay</a>
  </div>
</div>

<section id="landing-about" class="landing-section">

  <div class="container">
    <div class='row'>
      <div class='col-xs-12'>
        <div class="section-rant">
          <p>We are developers, designers, creatives, or entrepreneurs by
          trade. But we are do-gooders at heart.</p>
          <p><strong>Billion is where we band together to change the world.
          </strong></p>
        </div>
      </div>
    </div>

    <div class="row about-text-blocks">
      <div class="col-xs-12 col-sm-4">
        <div class="about-text-block">
          <div class="about-icon-block">
            <%= image_tag('stages/hand.png', :class => 'horizontalAlignCenter')  %>
          </div>
          <h4>Pitch & Rally</h4>
          <p>On launch day, pitch your BAM on billioneffect.com and
          start to rally votes from your friends and family.</p>
          <p>1 vote = $1.</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="about-text-block">
          <div class="about-icon-block">
            <%= image_tag('stages/bracket.png', :class => 'horizontalAlignCenter') %>
          </div>
          <h4>Bracket</h4>
          <p>The top 16 ideas will be funneled into a basketball style bracket.
          Votes from other BAMs will be reallocated by donors into the
          advancing movements.</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="about-text-block">
          <div class="about-icon-block">
            <%= image_tag('stages/person.png', :class => 'horizontalAlignCenter') %>
          </div>
          <h4>Crowdfund & Peoplesource</h4>
          <p>Once the winning billion movement is chosen, the community will
          begin traditional crowdfunding. Additionally, the community will
          volunteer skills and hours to support the billion movement. </p>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="landing-columbus" class="landing-section">
  <div class="container">
    <div class='row'>
      <div class="section-header">
        <h1>Coming to Columbus</h1>
      </div>
    </div>
    <div class='row'>
      <div class="col-sm-8 col-sm-offset-2 landing-columbus-text">
        <p>Billion is a platform for crowdfunding global initiatives. We’re
        starting at home to give back to our community. In our case,
        that’s the beautiful city of Columbus, Ohio.</p>
        <p>The first iteration of Billion will be held in the 614. The release
        date of our crowdfunding site will be up very soon. Make sure to join
        our email list and we’ll keep you updated. No spam, we promise.
        <%= icon('heart') %></p>
        <p>Start thinking of ideas to change Columbus. For good.</p>
      </div>
    </div>
  </div>
  <div class='landing-image-credit'>
    <a href='https://www.flickr.com/photos/janitors/9797078766/in/photolist-fVJAc9-fVJSra-fVJtSp-5dsK6G-ac6BX6-ac9tXw-ac9tZo-ac9tTj-ac9tCb-8d6J4v-5qoiju-5wFGdj-fYh8Zc-5HHLR5-5HDn4B-ancNFT-6ewBWz-6vJcoJ-45XdZ-6gukAv-bdi7ig-dbhvjn-6HCHVe-5T5Dcq-7ax4Qk-4QQsZn-cow5ab-dbhz37-4UfmUX-fSXDJr-8g2obH-4RxxKM-wkBFu-fPadC7-5HDrUF-5HDtRx-8d6Eu2-6FpuT2-ftdaKK-dBDFQA-8g5yzd-ftsB3S-8g5UE9-8g2tfZ-8g2BZ2-fq17Gg-6FtAQL-fTc8tF-4VF49P-7NpciA'>Image by Kārlis Dambrāns</a>
  </div>
</section>

<section id="landing-team" class="landing-section">
  <div class="container">
    <div class='row'>
      <div class="section-header">
        <h1>Get to know us</h1>
      </div>
    </div>

    <div class='row'>

      <div class='col-sm-4'>
        <div class='person-lg-container'>
          <div class='person-image'>
            <%= image_tag 'team/eileen.jpg' %>
          </div>
          <div class='person-bio'>
            <h2>Eileen Guan<small>CEO & Founder</small></h2>
            <p>Eileen is a UI/UX designer with a passion for solving impossible problems.
            A fourth-year student at Ohio State, she is a tech startup junkie with an
            unending love for building stuff and social entrepreneurship.</p>
          </div>
        </div>
      </div>

      <div class='col-sm-4'>
        <div class='person-lg-container'>
          <div class='person-image'>
            <%= image_tag 'team/alex.jpg' %>
          </div>
          <div class='person-bio'>
            <h2>Alex Vargas<small>CTO</small></h2>
            <p>Alex is a full-stack software engineer, passionate do-gooder,
            and full time dad to the coolest kid on the planet.</p>
          </div>
        </div>
      </div>

      <div class='col-sm-4'>
        <div class='person-lg-container'>
          <div class='person-image'>
            <%= image_tag 'team/ray.jpg' %>
          </div>
          <div class='person-bio'>
            <h2>Ray Li<small>COO</small></h2>
            <p>Ray is a recent graduate of Cornell University, where he studied physics and music.
            Ray is passionate about technology, innovation, and social good, and wants to develop
            platforms that deliver lasting changes for a better tomorrow.</p>
          </div>
        </div>
      </div>

      <div class='col-sm-4 col-md-2'>
        <div class='person-sm-container'>
          <div class='person-image'>
            <%= image_tag 'team/winnie.jpg' %>
          </div>
          <div class='person-bio'>
            <h2>Winnie Li<small>Marketing</small></h2>
          </div>
        </div>
      </div>

      <div class='col-sm-4 col-md-2'>
        <div class='person-sm-container'>
          <div class='person-image'>
            <%= image_tag 'team/michael.jpg' %>
          </div>
          <div class='person-bio'>
            <h2>Michael <small>Outreach</small></h2>
          </div>
        </div>
      </div>

      <div class='col-sm-4 col-md-2'>
        <div class='person-sm-container'>
          <div class='person-image'>
            <%= image_tag 'team/dicko.jpg' %>
          </div>
          <div class='person-bio'>
            <h2>Dicko Sow<small>Biz Dev</small></h2>
          </div>
        </div>
      </div>

      <div class='col-sm-4 col-md-2'>
        <div class='person-sm-container'>
          <div class='person-image'>
            <%= image_tag 'team/mark.jpg' %>
          </div>
          <div class='person-bio'>
            <h2>Mark<small>Back End Lead Developer</small></h2>
          </div>
        </div>
      </div>

      <div class='col-sm-4 col-md-2'>
        <div class='person-sm-container'>
          <div class='person-image'>
            <%= image_tag 'team/justin.jpg' %>
          </div>
          <div class='person-bio'>
            <h2>Justin<small>Front End Lead Developer</small></h2>
          </div>
        </div>
      </div>

      <div class='col-sm-4 col-md-2'>
        <div class='person-sm-container'>
          <div class='person-image'>
            <%= image_tag 'team/allen.jpg' %>
          </div>
          <div class='person-bio'>
            <h2>Allen White<small>Developer</small></h2>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

<section id="landing-join" class="landing-section">
  <div class="container">
    <div class='row'>
      <div class="section-header">
        <h1>Join the Movement</h1>
      </div>
    </div>
    <div class='row'>
      <div class="col-sm-8 col-sm-offset-2">
        <div class="alert alert-success hide" role="alert">
          <strong>Thanks for your support!</strong> We've sent you an email to
          confirm that you'd like to receive updates on our progress.
        </div>
      </div>
      <div class="col-sm-8 col-sm-offset-2 bd-danger">
        <div class="alert alert-danger hide" role="alert">
          Please enter a valid email address.
        </div>
      </div>
      <div class="col-sm-8 col-sm-offset-2 form-group">
        <form>
          <div class="input-group">
            <input type="email" class="form-control input-lg landing-email-input"
            placeholder="e.g. elonmusk@ironman.com"/>
            <span class="input-group-btn">
              <button class='btn btn-primary input-lg landing-email-submit'>
                <span class="landing-submit-text">Subscribe</span>
                <%= icon('spinner', '', class: 'fa-pulse hide') %>
              </button>
            </span>
          </div>
        </form>
      </div>
      <div class="col-sm-12 form-group landing-join-message">
        <p>We'll keep you updated on our progress.
        <a href='mailto:hello@billioneffect.com'>Still have questions? Ask away</a>
        </p>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class='row'>
      <div class="col-sm-2">
        <%= image_tag 'billion_logo_white_small.png' %>
      </div>
      <div class="col-sm-8">
        <p class="love">Made with
        <%= icon('heart') %>
        in Columbus, OH</p>
      </div>
      <div class="col-sm-2">
        <p class="social-links">
        <%= link_to icon('facebook'), 'https://www.facebook.com/billioneffect' %>
        <%= link_to icon('twitter'), 'https://twitter.com/BillionEffect' %>
        <%= link_to icon('instagram'), 'https://instagram.com/BillionEffect' %>
        </p>
      </div>
    </div>
  </div>
</footer>

<div id="modalVideo" class="modal fade">
  <div class="modal-dialog">
    <div id="modalVideoHeader">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
    <div id='embedVideo' class='embed-container'>
      <iframe src='https://www.youtube.com/embed/m68_iXKX5Ag' frameborder='0' allowfullscreen></iframe>
    </div>
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->